version: '2'

services:

  database:
    build:
      context: ./
      dockerfile: db.dockerfile
    domainname: kkday.dev
    container_name: kkday-db
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./restoredb:/restoredb
    ports:
      - 5432:5432
    expose:
      - 5432
  cache:
    image: redis:3.2.12-alpine3.8
    domainname: kkday.dev
    container_name: kkday-cache
    ports:
      - 6379:6379
    expose:
      - 6379

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www/html
    domainname: kkday.dev
    container_name: kkday-app
    volumes:
      - "${WORK_DIR}:/var/www/html"
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=kkday-db"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=kkday-cache"
    links:
      - database
      - cache

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www/html
    domainname: kkday.dev
    container_name: kkday-web
    volumes_from:
      - app
    ports:
      - 8080:80
    links:
      - app

  builder:
    image: composer:latest
    domainname: kkday.dev
    container_name: kkday-build
    volumes:
      - "${WORK_DIR}:/var/www/html"
    command: >
      bash -c "composer install -d /var/www/html
      && php /var/www/html/artisan migrate"
    depends_on:
        - app
